version: '3' 

services: 
  database:
    container_name: postgres
    image: postgres
    env_file:
      - postgres.env
    volumes:
    - database-data:/var/lib/postgresql/data
  
  jira:
    container_name: jira 
    image: atlassian/jira-software:latest 
    restart: always
    ports:
      - "8080:8080"
    environment:
     - ATL_TOMCAT_SCHEME=http 
     - JVM_MINIMUM_MEMORY=2048m
     - JVM_MAXIMUM_MEMORY=8192m


  jiraservicedesk:
    container_name: jiraservicedesk 
    image: atlassian/jira-servicedesk:latest 
    restart: always
    ports:
      - "8081:8081"
    environment:
     - ATL_TOMCAT_SCHEME=http 
     - JVM_MINIMUM_MEMORY=2048m
     - JVM_MAXIMUM_MEMORY=8192m

  confluence: 
    container_name: confluence
    image: atlassian/confluence-server:latest
    restart: always
    ports:
      - "8090:8090"
    environment: 
     - ATL_TOMCAT_SCHEME=http
     - JVM_MINIMUM_MEMORY=2048m
     - JVM_MAXIMUM_MEMORY=8192m

  bitbucket: 
    container_name: bitbucket 
    image: atlassian/bitbucket-server:latest 
    restart: always
    ports:
      - "7990:7990"
    environment:
     - JVM_MINIMUM_MEMORY=2048m
     - JVM_MAXIMUM_MEMORY=8192m
     - SERVER_SCHEME=http 

volumes:
  database-data: